name: Integration tests
on:
  workflow_dispatch:
  push:
    branches: ['main']

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Run "integration test" that submits all dependencies to this repository.
# This includes all uv.lock files in the test/ directory.
#
# Results can be seen in the dependency graph of this project.
# Repository dependabot rule is configured to dismiss security alerts from test/ files.
# Dependabot is configured to not create update PRs for test/ files.
jobs:
  submit:
    name: Submit test data
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: write # needs to submit dependency graph data
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Submit uv dependencies
        uses: ./
